#ifndef SOUNDLINK_PUNCTURE_H
#define SOUNDLINK_PUNCTURE_H

#include <stdint.h>
#include <stddef.h>

namespace soundlink{
/* 8-bit parity lookup table, generated by partab.c */
typedef unsigned char u8;

const uint16_t TRACEBACK = 184;
const uint16_t BUFFER_LEN = 1024;
const uint16_t OUTPUT_LEN_BYTES = (BUFFER_LEN - TRACEBACK) >> 3;
const uint16_t INPUT_BUFFER = 2 * (BUFFER_LEN - TRACEBACK);
const uint16_t INPUT_BUFFER_EXT = INPUT_BUFFER + 30;


unsigned char d_Partab[] = {
 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,1, 0, 0, 1, 0, 1, 1, 0,
};


const bool pu_pattern_1_2[] = { 1,1 };
const bool pu_pattern_2_3[] = { 1,1,0,1 };
const bool pu_pattern_3_4[] = { 1,1,0,1,1,0 };
const bool pu_pattern_5_6[] = { 1,1,0,1,1,0,0,1,1,0 };
const bool pu_pattern_7_8[] = { 1,1,0,1,0,1,0,1,1,0,0,1,1,0 };

const bool* patterns[] = {
	pu_pattern_1_2,
	pu_pattern_2_3,
	pu_pattern_3_4,
	pu_pattern_5_6,
	pu_pattern_7_8
};

#define ERASURE 0x80

size_t punc_1_2(const u8* __restrict in, u8* __restrict out, uint16_t& offset) {
    size_t in_idx = 0;
    size_t out_idx = offset;
    for (;offset < INPUT_BUFFER - 1; offset += 2) {
        out[out_idx++] = in[in_idx++]; // 1
        out[out_idx++] = in[in_idx++]; // 1
    }
    offset = offset - INPUT_BUFFER;
    return in_idx;
}

size_t punc_2_3(const u8* __restrict in, u8* __restrict out, uint16_t& offset) {
    size_t in_idx = 0;
    size_t out_idx = offset;
    for (;offset < INPUT_BUFFER - 1; offset += 4) {
        out[out_idx++] = in[in_idx++];   // 1
        out[out_idx++] = in[in_idx++];   // 1
        out[out_idx++] = ERASURE;      // 0
        out[out_idx++] = in[in_idx++];   // 1
    }
    offset = offset - INPUT_BUFFER;
    return in_idx;
}

size_t punc_3_4(const u8* __restrict in, u8* __restrict out, uint16_t& offset) {
    size_t in_idx = 0;
    size_t out_idx = offset;
    for (;offset < INPUT_BUFFER; offset += 6) {
        out[out_idx++] = in[in_idx++];  // 1
        out[out_idx++] = in[in_idx++];  // 1
        out[out_idx++] = ERASURE;     // 0
        out[out_idx++] = in[in_idx++];  // 1
        out[out_idx++] = in[in_idx++];  // 1
        out[out_idx++] = ERASURE;     // 0
    }
    offset = offset - INPUT_BUFFER;
    return in_idx;
}

size_t punc_5_6(const u8* __restrict in, u8* __restrict out, uint16_t& offset) {
    size_t in_idx = 0;
    size_t out_idx = offset;
    for (;offset < INPUT_BUFFER - 1; offset += 10) {
        out[out_idx++] = in[in_idx++];   // 1
        out[out_idx++] = in[in_idx++];   // 1
        out[out_idx++] = ERASURE;      // 0
        out[out_idx++] = in[in_idx++];   // 1
        out[out_idx++] = in[in_idx++];   // 1
        out[out_idx++] = ERASURE;      // 0
        out[out_idx++] = ERASURE;      // 0
        out[out_idx++] = in[in_idx++];   // 1
        out[out_idx++] = in[in_idx++];   // 1
        out[out_idx++] = ERASURE;      // 0
    }
    offset = offset - INPUT_BUFFER;
    return in_idx;
}

size_t punc_7_8(const u8* __restrict in, u8* __restrict out, uint16_t& offset) {
    size_t in_idx = 0;
    size_t out_idx = offset;
    for (;offset < INPUT_BUFFER - 1; offset += 14) {
        out[out_idx++] = in[in_idx++]; // 1
        out[out_idx++] = in[in_idx++]; // 1
        out[out_idx++] = ERASURE;      // 0
        out[out_idx++] = in[in_idx++]; // 1
        out[out_idx++] = ERASURE;      // 0
        out[out_idx++] = in[in_idx++]; // 1
        out[out_idx++] = ERASURE;      // 0
        out[out_idx++] = in[in_idx++]; // 1
        out[out_idx++] = in[in_idx++]; // 1
        out[out_idx++] = ERASURE;      // 0
        out[out_idx++] = ERASURE;      // 0
        out[out_idx++] = in[in_idx++]; // 1
        out[out_idx++] = in[in_idx++]; // 1
        out[out_idx++] = ERASURE;      // 0
    }
    offset = offset - INPUT_BUFFER;
    return in_idx;
}
}
#endif // !CONV_UTILS_H